# Generated by Django 6.1 on 2026-08-23 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatimages',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_log', to='api_data.chat'),
        ),
        migrations.AlterField(
            model_name='chatimages',
            name='image',
            field=models.ImageField(blank=True, upload_to='gens/'),
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.UniqueConstraint(fields=('account', 'chat_id'), name='unique_per_account'),
        ),
    ]
