# Generated by Django 6.1 on 2026-08-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0002_alter_chatimages_chat_alter_chatimages_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_id',
            field=models.CharField(max_length=32),
        ),
    ]
