# Generated by Django 6.1 on 2026-08-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0004_chatimages_log_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chatimages',
            constraint=models.UniqueConstraint(fields=('chat', 'log_id'), name='chat_unique'),
        ),
    ]
