# Generated by Django 6.1 on 2026-09-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0008_backfill_next_chat_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatimages',
            name='comparison_image',
            field=models.ImageField(blank=True, null=True, upload_to='gens/'),
        ),
    ]
