# Generated by Django 6.1 on 2026-09-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0009_chatimages_comparison_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
