# Generated by Django 6.1 on 2026-09-17 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0010_chat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='conditioning_strength',
            field=models.FloatField(default=0.8, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='chat',
            name='num_inference_steps',
            field=models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='chat',
            name='use_conditioning',
            field=models.BooleanField(default=True),
        ),
    ]
