# Generated by Django 6.1 on 2026-09-17 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0011_chat_conditioning_strength_chat_num_inference_steps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='conditioning_strength',
            field=models.FloatField(default=0.8, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='chat',
            name='num_inference_steps',
            field=models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
