# Generated by Django 6.1 on 2026-09-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0012_alter_chat_conditioning_strength_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='model_key',
            field=models.CharField(choices=[('sd-turbo', 'SD-Turbo'), ('sdxl-turbo', 'SDXL-Turbo'), ('tiny-sd', 'Tiny SD'), ('bk-sdm-small', 'BK-SDM Small')], default='sd-turbo', max_length=32),
        ),
    ]
