# Generated by Django 6.1 on 2026-09-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0013_chat_model_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='model_key',
            field=models.CharField(choices=[('sd-turbo', 'SD-Turbo'), ('sdxl-turbo', 'SDXL-Turbo'), ('flux2-klein', 'FLUX.2 Klein 4B (fp8)'), ('realvisxl-v5', 'RealVisXL V5.0')], default='sd-turbo', max_length=32),
        ),
    ]
