# Generated by Django 6.1 on 2026-09-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0014_alter_chat_model_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_key', models.CharField(max_length=40, unique=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
